import pyautogui

pyautogui.press('win')
pyautogui.sleep(1)
pyautogui.write('paint')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.moveTo(500,500)
pyautogui.sleep(1)
pyautogui.sleep(1)
pyautogui.dragRel(500,-0)
pyautogui.sleep(1)
pyautogui.dragRel(-100,-99)
pyautogui.sleep(1)
pyautogui.dragRel(-310,0)
pyautogui.sleep(1)
pyautogui.dragRel(95,100)
pyautogui.sleep(1)
pyautogui.dragRel(6,137)
pyautogui.sleep(1)
pyautogui.dragRel(310,-3)
pyautogui.sleep(1)
pyautogui.dragRel(-0,-137)
pyautogui.sleep(1)
pyautogui.dragRel(-100,-99)
pyautogui.sleep(1)
pyautogui.dragRel(-310,3)
pyautogui.sleep(1)
pyautogui.dragRel(-90,100)
pyautogui.sleep(1)
pyautogui.dragRel(0,137)
pyautogui.sleep(1)
pyautogui.dragRel(200,-0)

